version: "3.9"

services:
  qdpi-api:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - .:/app
    command: bash -c "pip install fastapi uvicorn[standard] && npm run api"
    ports:
      - "8000:8000" 